### ISSUE TITLE
Projectcore download site is down.

### ISSUE THREAD

**Issue by bdspark** [trentech/StackBan#20]
Stackban plugin seems nice. wanted to try. but cant download the projectcore. the site is down. 
requesting any alternative download link.

Thanks in advance

**Comment by trentech** [comment]
I've been moving stuff around. The forum posts all need to be updated.

http://trentech.org/jenkins/job/ProjectCore%20for%20SpongeAPI%207.x/

**Comment by bdspark** [comment]
Thank you for the link.

But i got some error when i try to use it.
Any advice to fix the error?

Thanks in advance.

18.08 21:21:31 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'sban' for source GCEntityPlayerMP['Hyder_'/13036, l='world', x=282.01, y=78.00, z=33.92]: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)Lorg/spongepowered/api/service/pagination/PaginationList;
18.08 21:21:31 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)Lorg/spongepowered/api/service/pagination/PaginationList;
18.08 21:21:31 [Server] INFO at com.gmail.trentech.pjc.help.Help.executeList(Help.java:297) ~[Help.class:?]
18.08 21:21:31 [Server] INFO at com.gmail.trentech.stackban.commands.CMDSBan.execute(CMDSBan.java:15) ~[CMDSBan.class:?]
18.08 21:21:31 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:177) ~[ChildCommandElementExecutor.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
18.08 21:21:31 [Server] INFO at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
18.08 21:21:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
18.08 21:21:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
18.08 21:21:31 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
18.08 21:21:31 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:238) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2558]
18.08 21:21:31 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3951) [MinecraftServer.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
18.08 21:21:31 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
18.08 21:21:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by trentech** [comment]
I think this commit broke something https://github.com/SpongePowered/SpongeAPI/commit/c4ead797895918d375855bb6124bc34786e00839
Might have to post on issue with Sponge
