### ISSUE TITLE
Found interface org.spongepowered.api.text.format.TextStyle, but class was expect

### ISSUE THREAD

**Issue by CaptainSoulo** [trentech/StackBan#27]
Hello, everytime I use any command from StackBan, I receive this:

> sban
[12:57:38] [Server thread/INFO] [minecraft/DedicatedServer]: Error occurred while executing command: Found interface org.spongepowered.api.text.format.TextStyle, but class was expected
[12:57:38] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'sban' for source DedicatedServer: Found interface org.spongepowered.api.text.format.TextStyle, but class was expected
java.lang.IncompatibleClassChangeError: Found interface org.spongepowered.api.text.format.TextStyle, but class was expected
        at com.gmail.trentech.pjc.help.Help.getStyle(Help.java:231) ~[Help.class:?]
        at com.gmail.trentech.pjc.help.Help.executeList(Help.java:258) ~[Help.class:?]
        at com.gmail.trentech.stackban.commands.CMDSBan.execute(CMDSBan.java:15) ~[CMDSBan.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-8.0.0-BETA-3402]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:329) [SpongeCommandManager.class:1.12.2-2705-8.0.0-BETA-3402]
        at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.executePendingCommands(DedicatedServer.java:432) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by CaptainSoulo** [comment]
The issue was due to the Sponge version I had installed. Using the stable release (7.0.0) Fixed it.
